/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaPrincipal.java
 *
 * Created on 31/10/2011, 09:39:18
 */
package view;

import control.BigBagCTR;
import model.domain.Ensaque;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import model.domain.Balanca;
import model.domain.BigBag;

/**
 *
 * @author Administrador
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private DefaultTableModel modeloTabela = null;

    private double contador = 0;
    private DecimalFormat formato = new DecimalFormat("#");
    
    /** Creates new form TelaPrincipal */
    public TelaPrincipal() {
        initComponents();
        
//        facadeBO = new FacadeBO(this);

        jTablePesagem.getColumnModel().getColumn(0).setPreferredWidth(200);
        jTablePesagem.getColumnModel().getColumn(1).setPreferredWidth(150); 
        jTablePesagem.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTablePesagem.getColumnModel().getColumn(3).setPreferredWidth(200);
        jTablePesagem.getColumnModel().getColumn(4).setPreferredWidth(300);

        modeloTabela = (DefaultTableModel) jTablePesagem.getModel();
        
        BigBagCTR bigBag1CTR = new BigBagCTR(this);
        bigBag1CTR.startCapturaEnsaqueBigBag1();

        BigBagCTR bigBag2CTR = new BigBagCTR(this);
        bigBag2CTR.startCapturaEnsaqueBigBag2();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesagem = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabelContador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PESAGEM DE ENSADEIRAS");

        jTablePesagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BALANCA", "CACAMBA", "NUM. ID SACO", "PESO LIQ.", "DATA HORA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePesagem);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("ZERAR");
        jButton1.setActionCommand("jButtonZerar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelContador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelContador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelContador.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelContador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabelContador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        contador = 0;
        jLabelContador.setText(formato.format(contador));
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelContador;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePesagem;
    // End of variables declaration//GEN-END:variables

    
    public void mostrarTela(Ensaque ensaque){
        
        String[] dados = new String [7];

        int cacamba = Integer.parseInt(ensaque.getNumBalanca());
            
        switch (cacamba) {
            case 1:
                dados[0] = "1";
                dados[1] = "1";
                break;
            case 2:
                dados[0] = "1";
                dados[1] = "2";
                break;
            case 4:
                dados[0] = "2";
                dados[1] = "1";
                break;
            case 5:
                dados[0] = "2";
                dados[1] = "2";
                break;
            case 6:
                dados[0] = "3";
                dados[1] = "1";
                break;
            case 7:
                dados[0] = "3";
                dados[1] = "2";
                break;
            default:
                dados[0] = "0";
                dados[1] = "0";
                break;
        }
        
        dados[2] = ensaque.getNumIDSaco();
        dados[3] = ensaque.getPesoLiq();
        dados[4] = ensaque.getData() + " " + ensaque.getHora();

        modeloTabela.insertRow(0, dados);

        if(modeloTabela.getRowCount() == 30){
            modeloTabela.removeRow(29);
        }

        contador = contador + 1;
        jLabelContador.setText(formato.format(contador));
        pack();
        
    }

    
}
